/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as DashboardRouteImport } from './../../routes/dashboard'
import { Route as IndexRouteImport } from './../../routes/index'
import { Route as DashboardIndexRouteImport } from './../../routes/dashboard.index'
import { Route as DashboardUsersRouteImport } from './../../routes/dashboard.users'
import { Route as DashboardTasksRouteImport } from './../../routes/dashboard.tasks'
import { Route as DashboardProfileRouteImport } from './../../routes/dashboard.profile'
import { Route as DashboardTasksIndexRouteImport } from './../../routes/dashboard.tasks.index'
import { Route as DashboardTasksOrderIdRouteImport } from './../../routes/dashboard.tasks.$orderId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTasksRoute,
} as any)
const DashboardTasksOrderIdRoute = DashboardTasksOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => DashboardTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tasks/$orderId': typeof DashboardTasksOrderIdRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/tasks/$orderId': typeof DashboardTasksOrderIdRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tasks/$orderId': typeof DashboardTasksOrderIdRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/profile'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/tasks/$orderId'
    | '/dashboard/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/profile'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/tasks/$orderId'
    | '/dashboard/tasks'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/profile'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/tasks/$orderId'
    | '/dashboard/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/'
      fullPath: '/dashboard/tasks/'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardTasksRoute
    }
    '/dashboard/tasks/$orderId': {
      id: '/dashboard/tasks/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/tasks/$orderId'
      preLoaderRoute: typeof DashboardTasksOrderIdRouteImport
      parentRoute: typeof DashboardTasksRoute
    }
  }
}

interface DashboardTasksRouteChildren {
  DashboardTasksOrderIdRoute: typeof DashboardTasksOrderIdRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
}

const DashboardTasksRouteChildren: DashboardTasksRouteChildren = {
  DashboardTasksOrderIdRoute: DashboardTasksOrderIdRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
}

const DashboardTasksRouteWithChildren = DashboardTasksRoute._addFileChildren(
  DashboardTasksRouteChildren,
)

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTasksRoute: typeof DashboardTasksRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTasksRoute: DashboardTasksRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
